### ISSUE TITLE
Calling SetupMatrices() from within Draw limits potential operations

### ISSUE THREAD

**Issue by HG-Dev** [AUTOMATIC1111/Rimlaser#8]
To stop a beam from appearing to pass through a shield it should be wrapping around or fizzling out upon, I had intended to work with the b Vector3 in the same way a is modified by the weapon's barrel length. This, however, requires identifying whether or not the usedTarget is wearing a shield belt, and this test appears to be unfit for use inside Draw. [(error here)](https://discordapp.com/channels/214523379766525963/215496692047413249/479589771094786048)

**I propose that a Verb inheriting largely from Verb_Shoot be created so that the LaserBeam projectile can run SetupMatrices before the Launch method is called.**

Yes, this would mean that the ugly namespace business would need to be added to weapon verb defs, but this would also present us with the ability to create custom def properties for a Rimlaser verb, rather than just projectiles. For instance, it may be worth applying a "piercing" boolean to the verb rather than the "bullet".

I'm prepared to open a new branch and hammer this out, but I'd like your input.

**Comment by HG-Dev** [comment]
The effects of this change, plus an added tesla gun buff, can be found here.
https://github.com/HG-Dev/Rimlaser/tree/verb_shootbeam

**Comment by AUTOMATIC1111** [comment]
this should be solved by the latest commit
